package org.example.project.ui.writersroom

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import org.example.project.domain.Script
import org.example.project.domain.ScriptDao
import org.example.project.domain.gemini.GeminiClient

class WritersRoomViewModel(
    private val scriptDao: ScriptDao,
    private val geminiClient: GeminiClient = GeminiClient()
) : ViewModel() {

    private val _activeScript = MutableStateFlow<Script?>(null)
    val activeScript: StateFlow<Script?> = _activeScript.asStateFlow()

    private val _isGenerating = MutableStateFlow(false)
    val isGenerating: StateFlow<Boolean> = _isGenerating.asStateFlow()

    private val _generatedScript = MutableStateFlow("")
    val generatedScript: StateFlow<String> = _generatedScript.asStateFlow()

    private val _targetDuration = MutableStateFlow(15)
    val targetDuration: StateFlow<Int> = _targetDuration.asStateFlow()

    private val _promptContent = MutableStateFlow("")
    val promptContent: StateFlow<String> = _promptContent.asStateFlow()

    init {
        viewModelScope.launch {
            scriptDao.getActiveScript().collect { script ->
                _activeScript.value = script
                if (script != null) {
                    if (_promptContent.value.isEmpty()) _promptContent.value = script.prompt
                    if (_generatedScript.value.isEmpty()) _generatedScript.value = script.content
                    if (script.targetDuration != null) _targetDuration.value = script.targetDuration
                }
            }
        }
    }

    fun generateScript() {
        viewModelScope.launch {
            _isGenerating.value = true
            try {
                val fullPrompt = "Write a script for YouTube short based on this premise: '${_promptContent.value}'. It should take exactly ${_targetDuration.value} seconds to read aloud at a normal pace. ONLY return the text to be spoken and the timestamp range it is spoken in, using the format '0s-5s: Hello...'. Do not include any conversational filler, markdown formatting, explanations, or background info."
                
                val script = geminiClient.generateScript(prompt = fullPrompt)
                _generatedScript.value = script
                saveDraft(clearMedia = true)
            } catch (e: Exception) {
                _generatedScript.value = "Error generating script: ${e.message}"
            } finally {
                _isGenerating.value = false
            }
        }
    }

    fun updateTargetDuration(duration: Int) {
        _targetDuration.value = duration
    }

    fun updatePromptContent(newPrompt: String) {
        _promptContent.value = newPrompt
    }

    fun updateScriptContent(newContent: String) {
        _generatedScript.value = newContent
    }

    private suspend fun saveDraft(clearMedia: Boolean = false) {
        val current = _activeScript.value
        val titleStr = _promptContent.value.takeIf { it.isNotBlank() }?.take(30) ?: "Generated Script"
        if (current != null) {
            val updated = current.copy(
                title = titleStr,
                prompt = _promptContent.value,
                content = _generatedScript.value,
                targetDuration = _targetDuration.value,
                isActive = true,
                videoPath = if (clearMedia) null else current.videoPath,
                skippedSegmentsJson = if (clearMedia) "" else current.skippedSegmentsJson
            )
            scriptDao.update(updated)
            _activeScript.value = updated
        } else {
            scriptDao.clearActiveScript()
            val newScript = Script(
                title = titleStr,
                prompt = _promptContent.value,
                content = _generatedScript.value,
                targetDuration = _targetDuration.value,
                isActive = true
            )
            scriptDao.insert(newScript)
            // Need to fetch it back to get the autogenerated ID, but active script flow will catch it
        }
    }

    fun saveScript(onSaved: () -> Unit) {
        viewModelScope.launch {
            saveDraft(clearMedia = false)
            onSaved()
        }
    }

    fun archiveScript() {
        val currentScript = _activeScript.value
        if (currentScript != null) {
            viewModelScope.launch {
                val updatedScript = currentScript.copy(scriptState = "ARCHIVED")
                scriptDao.update(updatedScript)
                _activeScript.value = null
                _promptContent.value = ""
                _generatedScript.value = ""
            }
        }
    }
}